
[package]
name = "LEDboardClient"
version = "0.1.0"
edition = "2021"

[dependencies]
bit = "0.1.1"
embedded-graphics = "0.8.0"
substring = "1.4.5"
tinybmp = "0.5.0"
openweathermap = { path = "../openweathermap" }
chrono = { version = "0.4.23", default-features = false , features = ["iana-time-zone"] }
chrono-tz = "0.8.0"
colored = "2.0.0"
datetime = "0.5.2"
